
/**
* Constants
*/
const Constants = {
    UPDATE_ROUND:"UPDATE_ROUND",
    UPDATE_PLAYER_SCORE:"UPDATE_PLAYER_SCORE",
    UPDATE_DEALER_SCORE:"UPDATE_DEALER_SCORE",
    UPDATE_WINNER:"UPDATE_WINNER",
    UPDATE_CARD:"UPDATE_CARD",
    INIT_CARD:"INIT_CARD",
    START_GAME:"START_GAME",
    INIT_SCORE:"INIT_SCORE",
    COUNTER:"COUNTER",
    DRAW_CARD_PLAYER:"DRAW_CARD_PLAYER",
    DRAW_CARD_DEALER:"DRAW_CARD_DEALER",
    STOP_RESTART_GAME:"STOP_RESTART_GAME"
};
export default Constants;
